### ISSUE TITLE
make-dist.py error

### ISSUE THREAD

**Issue by 789it789** [minexew/Shrine#13]
```
[chase@x220 Shrine-master]$ ./make-dist.py TOS_Distro.ISO Shrine ~/shrine.img 
Traceback (most recent call last):
  File "/home/chase/Downloads/Shrine-master/inject_templeos.py", line 6, in <module>
    from isoc import RedSea
  File "redseafs/isoc.py", line 22, in <module>
    from fuse import FUSE, FuseOSError, Operations, LoggingMixIn
ModuleNotFoundError: No module named 'fuse'
Traceback (most recent call last):
  File "./make-dist.py", line 121, in <module>
    subprocess.check_call([INJECT_BIN, PATCHED_ISO, 'Once.HC.Z', SLAVE_HC_Z])
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/chase/Downloads/Shrine-master/inject_templeos.py', 'TempleSlave.iso', 'Once.HC.Z', 'AutoOSInstall/SlaveOnce.HC.Z']' returned non-zero exit status 1.

```

**Comment by minexew** [comment]
You'll need to install a Python FUSE module. For example on Fedora you can use the package `python3-fuse`, or you can try to follow the instructions [here](https://github.com/minexew/Shrine/tree/master/redseafs#prerequisites).

Let me know what works for your distro, I'll add it to the readme.
