### ISSUE TITLE
FUSE?

### ISSUE THREAD

**Issue by jibanes** [minexew/Shrine#18]
$ sudo pip install fuse
[...]
$ ./make-dist.py TOS_Distro.ISO Shrine ~/shrine.img 
Traceback (most recent call last):
  File "/home/jibanes/Downloads/Shrine-master/inject_templeos.py", line 6, in <module>
    from isoc import RedSea
  File "redseafs/isoc.py", line 22, in <module>
    from fuse import FUSE, FuseOSError, Operations, LoggingMixIn
ImportError: cannot import name 'FUSE'
Traceback (most recent call last):
  File "./make-dist.py", line 121, in <module>
    subprocess.check_call([INJECT_BIN, PATCHED_ISO, 'Once.HC.Z', SLAVE_HC_Z])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/jibanes/Downloads/Shrine-master/inject_templeos.py', 'TempleSlave.iso', 'Once.HC.Z', 'AutoOSInstall/SlaveOnce.HC.Z']' returned non-zero exit status 1

**Comment by minexew** [comment]
See #13
