### ISSUE TITLE
ImportError: cannot import name 'FUSE' from 'fuse' (/usr/lib/python3/dist-packages/fuse.py)

### ISSUE THREAD

**Issue by arkadiyjs** [minexew/Shrine#27]
Tried to execute `make` after following [these](https://github.com/minexew/Shrine/tree/master/redseafs#prerequisites) instructions.

```
Traceback (most recent call last):
  File "/home/arkadiy/Shrine/inject_templeos.py", line 6, in <module>
    from isoc import RedSea
  File "redseafs/isoc.py", line 22, in <module>
    from fuse import FUSE, FuseOSError, Operations, LoggingMixIn
ImportError: cannot import name 'FUSE' from 'fuse' (/usr/lib/python3/dist-packages/fuse.py)
Traceback (most recent call last):
  File "make-dist.py", line 121, in <module>
    subprocess.check_call([INJECT_BIN, PATCHED_ISO, 'Once.HC.Z', SLAVE_HC_Z])
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/arkadiy/Shrine/inject_templeos.py', 'TempleSlave.iso', 'Once.HC.Z', 'AutoOSInstall/SlaveOnce.HC.Z']' returned non-zero exit status 1
make: *** [Makefile:2: build] Error 1
```

### Additional info
OS: Debian GNU/Linux buster/sid
Python: 2.7.16rc1 and 3.7.2+
QEMU: 1:3.1+dfsg-4

**Comment by minexew** [comment]
Yeah, we keep dealing with this shit over and over (#13, #18).

If you are able to find out what works for you, I'll add it to the readme.

**Comment by arkadiyjs** [comment]
I've already gone through those before submitting this issue. This specific ImportError does not come up in the aforementioned reports.

**Comment by minexew** [comment]
Were you able to find a solution?

**Comment by arkadiyjs** [comment]
No

**Comment by minexew** [comment]
Sucks to be you! Ahahaha!
