### ISSUE TITLE
Failed to build with python3 ./make-dist.py

### ISSUE THREAD

**Issue by JPStech** [minexew/Shrine#29]
Following instructions i was able to make shrine.img but installing i get an error:

--- 15:08:31 -- user@comp: ~/Downloads/Shrine-master$ sudo python3 ./make-dist.py TOS_Distro.ISO Shrine ~/shrine.img

Traceback (most recent call last):
  File "/home/user/Downloads/Shrine-master/inject_templeos.py", line 6, in <module>
    from isoc import RedSea
  File "redseafs/isoc.py", line 22, in <module>
    from fuse import FUSE, FuseOSError, Operations, LoggingMixIn
  File "/usr/local/lib/python3.5/dist-packages/fuse/__init__.py", line 3, in <module>
    from .defect_augment import DefectAugment
  File "/usr/local/lib/python3.5/dist-packages/fuse/defect_augment.py", line 11, in <module>
    from gunpowder import BatchFilter
  File "/usr/local/lib/python3.5/dist-packages/gunpowder/__init__.py", line 3, in <module>
    from . import nodes
  File "/usr/local/lib/python3.5/dist-packages/gunpowder/nodes/__init__.py", line 3, in <module>
    from .add_affinities import AddAffinities
  File "/usr/local/lib/python3.5/dist-packages/gunpowder/nodes/add_affinities.py", line 6, in <module>
    from gunpowder.ext import malis
  File "/usr/local/lib/python3.5/dist-packages/gunpowder/ext/__init__.py", line 51, in <module>
    import augment
  File "/usr/local/lib/python3.5/dist-packages/augment.py", line 181, in <module>
    def _surround(aux_fn, around=False, before=False, after=False):
  File "/usr/local/lib/python3.5/dist-packages/augment.py", line 130, in decorator
    allargs, fn_name = _get_args_and_name(fn)
  File "/usr/local/lib/python3.5/dist-packages/augment.py", line 37, in _get_args_and_name
    code = fn.func_code
AttributeError: 'function' object has no attribute 'func_code'
Traceback (most recent call last):
  File "./make-dist.py", line 121, in <module>
    subprocess.check_call([INJECT_BIN, PATCHED_ISO, 'Once.HC.Z', SLAVE_HC_Z])
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/user/Downloads/Shrine-master/inject_templeos.py', 'TempleSlave.iso', 'Once.HC.Z', 'AutoOSInstall/SlaveOnce.HC.Z']' returned non-zero exit status 1

**Comment by minexew** [comment]
That seems like some super obscure issue within FUSE's dependencies and does not seem Shrine specific. I can only recommend trying to update everything (Python 3.7 and all the packages) or looking up the core error (`AttributeError: 'function' object has no attribute 'func_code'`)

**Comment by minexew** [comment]
Due to the lack of activity in many months, and since Shrine 6 is getting a new build system, I will close this ticket for now.
