### ISSUE TITLE
Merge network driver improvements from Erythros

### ISSUE THREAD

**Issue by minexew** [minexew/Shrine#35]
What a piece of work in the first place!
https://github.com/obecebo/erythros/tree/master/System/Drivers/Net

**Comment by xslendix** [comment]
did u do it yet me cant wait also, 
``` bruh@moment  ~  ./snail.py   
Traceback (most recent call last):
  File "./snail.py", line 14, in <module>
    sock.connect((TCP_IP, TCP_PORT))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused
 ✘ bruh@moment  ~  ``` - how do i fix this? is in com3, 127.0.0.1, port 7777 wahts wrong

**Comment by minexew** [comment]
@xslendix Snail tunelled networking has always been a mess. You should try to use the native stack instead. But I am not sure why you are getting that specific error. Since you are alone, I'm thinking perhaps something changed recently in how VirtualBox works.
